project:
  type: website
  render:
    - "*.qmd"
    - "!snippets/"

website:
  title: "Ancient DNA Data Analysis - Workshop Uni Siegen 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

